name: SBS
options:
  minimumXcodeGenVersion: 2.36.0
  bundleIdPrefix: com.gregorymcinnes
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
packages: {}
targets:
  SBSApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SBSApp
      - path: SBSCore
      - path: Resources/sbs_program_config.json
        buildPhase: resources
      - path: Resources/nsuns_5day_12week.json
        buildPhase: resources
      - path: Resources/nsuns_4day_12week.json
        buildPhase: resources
      - path: Resources/531_bbb_12week.json
        buildPhase: resources
      - path: Resources/531_triumvirate_12week.json
        buildPhase: resources
      - path: Resources/gzclp_12week.json
        buildPhase: resources
      - path: Resources/gzclp_3day_12week.json
        buildPhase: resources
      - path: Resources/stronglifts_5x5_12week.json
        buildPhase: resources
      - path: Resources/greyskull_lp_12week.json
        buildPhase: resources
      - path: Resources/reddit_ppl_12week.json
        buildPhase: resources
      - path: Resources/starting_strength_12week.json
        buildPhase: resources
      - path: Resources/powerlifting_percentiles.json
        buildPhase: resources
    dependencies:
      - target: RestTimerWidget
        embed: true
      - target: SBSWatch
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gregorymcinnes.topsettraining
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2K7MV7G4ZJ
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    scheme:
      storeKitConfiguration: SBS.storekit
    entitlements:
      path: SBSApp/SBSApp.entitlements
      properties:
        com.apple.developer.healthkit: true
    info:
      path: SBSApp/Info.plist
      properties:
        CFBundleName: Top Set Training
        CFBundleDisplayName: Top Set Training
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSSupportsLiveActivities: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        NSHealthShareUsageDescription: Top Set Training uses HealthKit to read your workout history and heart rate data during workouts.
        NSHealthUpdateUsageDescription: Top Set Training uses HealthKit to automatically log your strength training workouts to Apple Fitness, tracking duration and workout completion.

  RestTimerWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RestTimerWidget
      - path: SBSCore/RestTimerActivity.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gregorymcinnes.topsettraining.RestTimerWidget
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: RestTimerWidget/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Rest Timer
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2K7MV7G4ZJ
    info:
      path: RestTimerWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true

  SBSWatch:
    type: application
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: SBSWatch
      - path: SBSCore/HealthKitManager.swift
      - path: SBSCore/Logger.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gregorymcinnes.topsettraining.watchkitapp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2K7MV7G4ZJ
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.gregorymcinnes.topsettraining
        INFOPLIST_KEY_WKRunsIndependentlyOfCompanionApp: false
    entitlements:
      path: SBSWatch/SBSWatch.entitlements
      properties:
        com.apple.developer.healthkit: true
    info:
      path: SBSWatch/Info.plist
      properties:
        CFBundleName: Top Set Training
        CFBundleDisplayName: Top Set Training
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.gregorymcinnes.topsettraining
        NSHealthShareUsageDescription: Top Set Training uses HealthKit to track your heart rate during workouts.
        NSHealthUpdateUsageDescription: Top Set Training uses HealthKit to automatically log your strength training workouts.

  SBSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SBSTests
      - path: SBSCore
    dependencies:
      - target: SBSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gregorymcinnes.topsettraining.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SBSApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/SBSApp
        BUNDLE_LOADER: $(TEST_HOST)
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2K7MV7G4ZJ
